services:
  db:
    container_name: constructor_db
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    container_name: backend
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./.env.dev
    restart: unless-stopped

    ports:
      - '8000:8000'

    volumes:
      - .:/code

volumes:
  postgres_data: